server:
  port: 7786
spring:
  application:
    name: thinking-in-mybatisplus
  datasource:
    # 使用阿里的Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
    username: root
    password: 12345678
    druid:
      #配置可视化控制台页面
      stat-view-servlet:
        enabled: true
        #访问德鲁伊监控页面的地址
        url-pattern: /druid/*
        #IP白名单 没有配置或者为空 则允许所有访问
        allow:
        #IP黑名单 若白名单也存在 则优先使用
        deny:
        #禁用重置按钮
        reset-enable: true
        #登录所用的用户名与密码
        login-username: admin
        login-password: 123456
      web-stat-filter: # Druid Web统计过滤器配置
        enabled: true # 启用Web统计过滤器
        session-stat-enable: true # 启用会话统计功能
        session-stat-max-count: 1000 # 最大会话统计数量
      filter: # Druid过滤器配置
        stat: # SQL统计过滤器配置
          enabled: true # 启用SQL统计过滤器
          log-slow-sql: true # 启用慢SQL日志记录
          slow-sql-millis: 10 # 慢SQL的执行时间阈值（单位：毫秒）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
